export const seedData = {
  users: {
    _model: "User",
    sheldon: {
      firstName: "Sheldon",
      secondName: "Cooper",
      email: "sheldon.cooper@caltechmail.com",
      password: "Bazinga123!",
    },
    leonard: {
      firstName: "Leonard",
      secondName: "Hofstadter",
      email: "leonard.hofstadter@physicsmail.org",
      password: "Roommate456!",
    },
    howard: {
      firstName: "Howard",
      secondName: "Wolowitz",
      email: "howard.wolowitz@aerospacehub.net",
      password: "Rocket789!",
    },
    raj: {
      firstName: "Raj",
      secondName: "Koothrappali",
      email: "raj.koothrappali@cosmosmail.io",
      password: "Astro321!",
    },
  },
  plants: {
    _model: "Plant",

    // Sheldon’s Plants
    sunflower: {
      commonName: "Sunflower",
      scientificName: "Helianthus annuus",
      type: "Flower",
      biome: "Meadow",
      imageUrls: ["https://picsum.photos/200"],
      note: "Grows tall and loves sunlight",
      latitude: 48.8566,
      longitude: 2.3522,
      userId: "->users.sheldon",
    },
    oak: {
      commonName: "Oak Tree",
      scientificName: "Quercus robur",
      type: "Tree",
      biome: "Forest",
      imageUrls: ["https://picsum.photos/200"],
      note: "Can live for hundreds of years",
      latitude: 51.5074,
      longitude: -0.1278,
      userId: "->users.sheldon",
    },
    lavender: {
      commonName: "Lavender",
      scientificName: "Lavandula angustifolia",
      type: "Flower",
      biome: "Meadow",
      imageUrls: ["https://picsum.photos/200"],
      note: "Fragrant and purple",
      latitude: 48.8566,
      longitude: 2.3522,
      userId: "->users.sheldon",
    },
    moss: {
      commonName: "Cushion Moss",
      scientificName: "Leucobryum glaucum",
      type: "Moss",
      biome: "Forest",
      imageUrls: ["https://picsum.photos/200"],
      note: "Soft green moss",
      latitude: 48.8566,
      longitude: 2.3522,
      userId: "->users.sheldon",
    },

    // Leonard’s Plants
    ivy: {
      commonName: "Ivy",
      scientificName: "Hedera helix",
      type: "Climber",
      biome: "Urban",
      imageUrls: ["https://picsum.photos/200"],
      note: "Climbs walls and fences",
      latitude: 40.7128,
      longitude: -74.006,
      userId: "->users.leonard",
    },
    fern: {
      commonName: "Boston Fern",
      scientificName: "Nephrolepis exaltata",
      type: "Fern",
      biome: "Other",
      imageUrls: ["https://picsum.photos/200"],
      note: "Lush indoor foliage",
      latitude: 40.7128,
      longitude: -74.006,
      userId: "->users.leonard",
    },
    grass: {
      commonName: "Kentucky Bluegrass",
      scientificName: "Poa pratensis",
      type: "Grass",
      biome: "Meadow",
      imageUrls: ["https://picsum.photos/200"],
      note: "Classic lawn grass",
      latitude: 40.7128,
      longitude: -74.006,
      userId: "->users.leonard",
    },

    // Howard’s Plants
    waterLily: {
      commonName: "Water Lily",
      scientificName: "Nymphaea alba",
      type: "Aquatic Plant",
      biome: "Pond",
      imageUrls: ["https://picsum.photos/200"],
      note: "Floats on water, blooms in summer",
      latitude: 45.4215,
      longitude: -75.6972,
      userId: "->users.howard",
    },
    aloe: {
      commonName: "Aloe Vera",
      scientificName: "Aloe vera",
      type: "Other",
      biome: "Desert",
      imageUrls: ["https://picsum.photos/200"],
      note: "Medicinal succulent",
      latitude: 45.4215,
      longitude: -75.6972,
      userId: "->users.howard",
    },
    cactus: {
      commonName: "Cactus",
      scientificName: "Cactaceae",
      type: "Other",
      biome: "Desert",
      imageUrls: ["https://picsum.photos/200"],
      note: "Survives hot and dry conditions",
      latitude: 45.4215,
      longitude: -75.6972,
      userId: "->users.howard",
    },

    // Raj’s Plants
    jade: {
      commonName: "Jade Plant",
      scientificName: "Crassula ovata",
      type: "Other",
      biome: "Urban",
      imageUrls: ["https://picsum.photos/200"],
      note: "Popular houseplant",
      latitude: 34.0522,
      longitude: -118.2437,
      userId: "->users.raj",
    },
    monstera: {
      commonName: "Monstera",
      scientificName: "Monstera deliciosa",
      type: "Climber",
      biome: "Other",
      imageUrls: ["https://picsum.photos/200"],
      note: "Swiss-cheese plant",
      latitude: 34.0522,
      longitude: -118.2437,
      userId: "->users.raj",
    },
    fern2: {
      commonName: "Maidenhair Fern",
      scientificName: "Adiantum",
      type: "Fern",
      biome: "Forest",
      imageUrls: ["https://picsum.photos/200"],
      note: "Delicate indoor fern",
      latitude: 34.0522,
      longitude: -118.2437,
      userId: "->users.raj",
    },
  },
  collections: {
    _model: "Collection",
    sheldonGarden: {
      name: "Sheldon’s Garden",
      description: "Sheldon’s plants",
      imageUrl: "https://picsum.photos/200",
      userId: "->users.sheldon",
      plantIds: ["->plants.sunflower", "->plants.oak", "->plants.lavender", "->plants.moss"],
    },
    leonardIndoor: {
      name: "Leonard’s Indoor Plants",
      description: "Leonard’s plants",
      imageUrl: "https://picsum.photos/200",
      userId: "->users.leonard",
      plantIds: ["->plants.ivy", "->plants.fern", "->plants.grass"],
    },
    howardHerbs: {
      name: "Howard’s Water & Desert Plants",
      description: "Howard’s plants",
      imageUrl: "https://picsum.photos/200",
      userId: "->users.howard",
      plantIds: ["->plants.waterLily", "->plants.aloe", "->plants.cactus"],
    },
    rajSucculents: {
      name: "Raj’s Indoor Succulents",
      description: "Raj’s plants",
      imageUrl: "https://picsum.photos/200",
      userId: "->users.raj",
      plantIds: ["->plants.jade", "->plants.monstera", "->plants.fern2"],
    },
  },
};
